import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "./providers";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`max-w-6xl mx-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-20 mx-auto">
          <TanstackProvider>
            <Toaster position="top-center" richColors/>
            {children}
          </TanstackProvider>
        </div>
      </body>
    </html>
  );
}
