@baseUrl=http://localhost:8080

###
GET {{baseUrl}}

###

GET {{baseUrl}}/user/9786

### 
POST {{baseUrl}}/user
Content-Type: application/json

{
  "Name" : "name",
  "Email": "sfafasfamapafle@gmail.com"
}