@baseUrl=http://localhost:8080

###
GET {{baseUrl}}

###

GET {{baseUrl}}/user/1

### 
POST {{baseUrl}}/user
Content-Type: application/json

{
  "Name" : "nafame",
  "Email": "sffaefawdfafewsfafqmapafle@gmail.com"
}

###

GET {{baseUrl}}/post

###
GET {{baseUrl}}/post/7

###

POST {{baseUrl}}/post
Content-Type: application/json

{
  "title": "titlefa",
  "content": "confatent",
  "user_id": 1,
}

###
DELETE {{baseUrl}}/post/39

###
PUT {{baseUrl}}/post/61
Content-Type: application/json

{
  "title": "fa",
  "content":"contentfaesijf",
  "user_id": 1
}

###
GET {{baseUrl}}/post/111/comments

###
POST {{baseUrl}}/post/111/comment
Content-Type: application/json

{
  "title": "fafa",
  "content":"comuibubment",
  "author_id": 43
}