@baseUrl=http://localhost:8080

###
GET {{baseUrl}}

###

GET {{baseUrl}}/user/34

### 
POST {{baseUrl}}/user
Content-Type: application/json

{
  "Name" : "name",
  "Email": "sfafasfafqmapafle@gmail.com"
}

###

GET {{baseUrl}}/post

###
GET {{baseUrl}}/post/7

###

POST {{baseUrl}}/post
Content-Type: application/json

{
  "title": "title",
  "content": "content"
}